apiVersion: v1
kind: Pod
metadata:
  labels:
    app: httpserver
  name: httpserver
spec:
  containers:
    -  name: httpserver
       image: httpserver:0.0.1
       imagePullPolicy: Never
       resources:
         limits:
           memory: 512Mi
           cpu: 200m
         requests:
           memory: 256Mi
           cpu: 100m

       readinessProbe:
         httpGet:
           port: 8080
         initialDelaySeconds: 10
         periodSeconds: 5
       lifecycle:
         preStop:
           exec:
             command: [ "/bin/sh", "-c", "while killall -0 httpserver;do sheep 1;done"]
